### ISSUE TITLE
Make a PICO-8 demo of sharing something

### ISSUE THREAD

**Issue by HuangJunye** [QPong/planning#16]

**Comment by Unathi-Skosana** [comment]
## Tasks
- [ ] Get acquainted with PICO-8 [pico-8/awesome-pico-8](https://github.com/pico-8/awesome-PICO-8
- [ ] Research how to extract game data from a web-hosted pico-8 game to the player's clipboard [awesome/clipboard](https://github.com/freehaha/awesome-clipboard) and [gist](https://gist.github.com/XNORGATE/9944afe7da4ff915b8158ac7c0518714)
- [ ] Build a basic pico-8 a demonstrating the above (either hosted on itch.io or self hosted like [http://zachpetersendev.com/picarioGame/](zachpetersendev.com/picarioGame)?)

To the second check list item; Alternatively, one could instead build a pico-8 in JS/TS [https://jspicl.github.io/](jspicl) and leave the sharing (which I presume in such a scenario,  TS/JS would be managing the game state to certain extant) to TS/JS.

**Comment by Unathi-Skosana** [comment]
It appears as if global libraries such as `os` and `io` that are within scope in vanilla Lua, are intentionally disabled in pico-8 for obvious security reasons, which I think would make copying text to the OS's clipboard or opening a url link (as in the comment on issue #15,  for posting on twitter) from a pico-8 impossible, if not very difficult to achieve. See [gist](https://gist.github.com/Unathi-Skosana/ac3ab0e584f6ee815b77c9edbc5f9c5c): 

```lua
-- attempts to open a given url in the system default browser, regardless of operating system.
local open_cmd -- this needs to stay outside the function, or it'll re-sniff every time...
function _open_url(url)
 if not open_cmd then
     if package.config:sub(1,1) == '\\' then -- windows
         open_cmd = function(url)
             -- should work on anything since (and including) win'95
             os.execute(string.format('start "%s"', url))
         end
     -- the only systems left should understand uname...
     elseif (io.popen("uname -s"):read'*a') == "darwin" then -- osx/darwin ? (i can not test.)
         open_cmd = function(url)
             -- i cannot test, but this should work on modern macs.
             os.execute(string.format('open "%s"', url))
         end
     else -- that ought to only leave linux
         open_cmd = function(url)
             -- should work on x-based distros.
             os.execute(string.format('xdg-open "%s"', url))
         end
     end
 end

 open_cmd(url)
end
```

This code excerpt works on vanilla Lua, but not on pico-8 :(

**Comment by Unathi-Skosana** [comment]
As an alternative, I think we should consider QPong writing QPong in a web-based language like JS/TS, in the future, this would make QPong's codebase a little more malleable for adding features such as multi-player, score sharing, analytics, etc. To this end,  a game framework like [phaser.io](https://phaser.io/) immediately comes to mind.

**Comment by HuangJunye** [comment]
- Explore in pico-8 community how to open url or copy paste without using standard library
- Explore wrapping in javascript

**Comment by Unathi-Skosana** [comment]
As discussed during #33 , the best (or only possible way) way to implement such a feature for a pico8 game is to send the data (score, player ids, and etc) to the frontend (JS), where opening/sharing URL links will be done. This can be achieved by encoding data in bytes and populating the `pico8_gpio` array with the said data, and retrieving from the client by reading `pico8_gpio` array (as done [here](http://zachpetersendev.com/picarioGame)). 

However, to proceed with the above requires purchasing pico8 for exporting games to html and more importantly the JS for testing changes that implement the just described feature (on [pico-edu](https://www.pico-8-edu.com/) export is not supported). Alternatively, one could locally editing the once-off exported JS (thanks @HuangJunye) to reflect the changes made in the pico8 game source code (see source [here](https://gist.github.com/Unathi-Skosana/89a2f0b4682c6d1dbda328a2bf6b84b4)), but this is pulling teeth since much of the pico-8 game source code (as far as I can tell) is compiled down to a large JS with a lot of moving parts even for a basic demo, which is hard to read and it is not yet clear to me where to start (see [gist](https://gist.github.com/Unathi-Skosana/20acc73d7fad9deee1080bfdefe60158))

**Comment by tula3and** [comment]
Good source to send data to apply for server

- https://github.com/joshiemoore/p8modem
- https://github.com/JRJurman/pico-socket

It is found by Unathi. Thanks again!

**Comment by tula3and** [comment]
Using p8modem; checked it works well.

![Image](https://user-images.githubusercontent.com/62553200/199383483-3d54541d-520c-4803-88dc-b5b9c9e8feda.png)

However, sending an array is not working.
